trigger:
- main

pool:
  name: 'my-agent'

jobs:
- job: Build_SonarQubeAnalysis_PushToDockerHub
  displayName: 'Build, Push to Docker Hub, and SonarQube Analysis'
  steps:
  - checkout: self

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
    displayName: 'Build Java Application'
  
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'sonarqube'
      scannerMode: 'Other'
    displayName: 'Prepare SonarQube Analysis'
    
  - script: 'mvn sonar:sonar'
    displayName: 'Run SonarQube Analysis'

 # Docker - Login to Docker Hub using Service Connection
  - task: Docker@2
    displayName: 'Docker Login to Docker Hub'
    inputs:
      command: 'login'
      containerRegistry: 'dockerHub' 
 
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerHub'
      repository: 'salmaal/backend'
      command: 'buildAndPush'
      Dockerfile: 'dockerfileboot'
   
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerHub'
      repository: 'salmaal/frontend'
      command: 'buildAndPush'
      Dockerfile: 'src/main/webapp/reactjs/dockerfilejs' 